###############################################################
#  Generated by:      Cadence Innovus 21.12-s106_1
#  OS:                Linux x86_64(Host ID iteso-server)
#  Generated on:      Thu Nov 30 04:15:23 2023
#  Design:            risc_v_Pad_Frame
#  Command:           create_ccopt_clock_tree_spec -file risc_v_Pad_Frame_ccopt_CTS.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   My_CLK (period 10.000ns) in timing_config ConstraintMode_WC([../Innovus_inputs/risc_v_Pad_Frame_opt.CM_risc_v_slow.sdc])
#   My_CLK (period 10.000ns) in timing_config ConstraintMode_BC([../Innovus_inputs/risc_v_Pad_Frame_opt.CM_risc_v_fast.sdc])
create_ccopt_clock_tree -name My_CLK -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner_WC -early -clock_tree My_CLK 0.400
set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner_WC -late -clock_tree My_CLK 0.550
set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner_BC -early -clock_tree My_CLK 0.400
set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner_BC -late -clock_tree My_CLK 0.550
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner DelayCorner_WC -early -rise -clock_tree My_CLK 0.200
set_ccopt_property source_latency -delay_corner DelayCorner_WC -early -fall -clock_tree My_CLK 0.150
set_ccopt_property source_latency -delay_corner DelayCorner_WC -late -rise -clock_tree My_CLK 0.200
set_ccopt_property source_latency -delay_corner DelayCorner_WC -late -fall -clock_tree My_CLK 0.150
set_ccopt_property source_latency -delay_corner DelayCorner_BC -early -rise -clock_tree My_CLK 0.200
set_ccopt_property source_latency -delay_corner DelayCorner_BC -early -fall -clock_tree My_CLK 0.150
set_ccopt_property source_latency -delay_corner DelayCorner_BC -late -rise -clock_tree My_CLK 0.200
set_ccopt_property source_latency -delay_corner DelayCorner_BC -late -fall -clock_tree My_CLK 0.150
# Clock period setting for source pin of My_CLK
set_ccopt_property clock_period -pin clk 10

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:My_CLK in timing_config:ConstraintMode_WC (sdc ../Innovus_inputs/risc_v_Pad_Frame_opt.CM_risc_v_slow.sdc)
create_ccopt_skew_group -name My_CLK/ConstraintMode_WC -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group My_CLK/ConstraintMode_WC true
set_ccopt_property target_insertion_delay -skew_group My_CLK/ConstraintMode_WC 0.600
set_ccopt_property extracted_from_clock_name -skew_group My_CLK/ConstraintMode_WC My_CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group My_CLK/ConstraintMode_WC ConstraintMode_WC
set_ccopt_property extracted_from_delay_corners -skew_group My_CLK/ConstraintMode_WC DelayCorner_WC

# Skew group to balance non generated clock:My_CLK in timing_config:ConstraintMode_BC (sdc ../Innovus_inputs/risc_v_Pad_Frame_opt.CM_risc_v_fast.sdc)
create_ccopt_skew_group -name My_CLK/ConstraintMode_BC -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group My_CLK/ConstraintMode_BC true
set_ccopt_property extracted_from_clock_name -skew_group My_CLK/ConstraintMode_BC My_CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group My_CLK/ConstraintMode_BC ConstraintMode_BC
set_ccopt_property extracted_from_delay_corners -skew_group My_CLK/ConstraintMode_BC DelayCorner_BC


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

