###############################################################
#  Generated by:      Cadence Innovus 21.12-s106_1
#  OS:                Linux x86_64(Host ID ip-172-31-46-123.us-east-2.compute.internal)
#  Generated on:      Wed Nov  8 04:12:49 2023
#  Design:            risc_v_Pad_Frame
#  Command:           saveDesign risc_v_Pad_Frame_power_ring.tcl
###############################################################
if {[is_common_ui_mode]} {
  read_db [file dirname [file normalize [info script]]]/risc_v_Pad_Frame_power_ring.tcl.dat
} else {
  restoreDesign [file dirname [file normalize [info script]]]/risc_v_Pad_Frame_power_ring.tcl.dat risc_v_Pad_Frame
}

