#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 21.10-p100 (15-Apr-2021) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: #Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
vpxmode
delete set_seq_merge
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[2]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[34] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[3]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[35] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[4]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[36] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[5]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[37] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[6]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[38] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[7]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[39] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[8]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[40] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[9]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[41] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[10]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[42] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[11]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[43] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[12]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[44] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[13]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[45] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[14]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[46] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[15]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[47] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[16]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[48] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[17]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[49] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[18]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[50] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[19]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[51] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[20]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[52] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[21]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[53] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[22]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[54] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[23]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[55] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[24]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[56] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[25]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[57] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[26]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[58] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[27]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[59] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[28]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[60] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[29]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[61] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[30]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[62] -Golden
set_seq_merge /risc_v_top_i/ex_mem_datapath_ffd_q_reg[31]  /risc_v_top_i/ex_mem_datapath_ffd_q_reg[63] -Golden
tclmode
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE risc_v_Pad_Frame (G) INSTANCE / (G)
# MODULE risc_v_Pad_Frame (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) rst_n (REP)  =   (R) rst_n (REP) (by name)
# IN (G) rx (REP)  =   (R) rx (REP) (by name)
# RESOLVED Constraints
# OUT (G) tx (REP)  =   (R) tx (REP) (by name)
# RESOLVED Constraints
# IO (G) VDD1 (REP)  =   (R) VDD1 (REP) (by name)
# IO (G) VSS1 (REP)  =   (R) VSS1 (REP) (by name)
# IO (G) VDDIOR1 (REP)  =   (R) VDDIOR1 (REP) (by name)
# IO (G) VSSIOR1 (REP)  =   (R) VSSIOR1 (REP) (by name)
set_root_module risc_v_Pad_Frame -Golden
set_root_module risc_v_Pad_Frame -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following modules are not written  because they have been added as black box:
# PADVDD (G)
# PADVSS (G)
# PADVDDIOR (G)
# PADVSSIOR (G)
# padIORINGCORNER (G)
# PADVDD (R)
# PADVDDIOR (R)
# PADVSS (R)
# PADVSSIOR (R)
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# ffd_param_clear_n_LENGTH206 (Instance: risc_v_top_i/ex_mem_datapath_ffd) (G)
# instr_memory_DATA_WIDTH32_ADDR_WIDTH10 (Instance: risc_v_top_i/memory_rom) (G)
# uart_tx_baud_rate5210 (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/tx_uart) (G)
# imm_gen (Instance: risc_v_top_i/immediate_gen) (G)
# Bit_Rate_Pulse_delay_counts5210 (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/tx_uart/baudrate_counter) (G)
# data_memory_DATA_WIDTH32_ADDR_WIDTH9 (Instance: risc_v_top_i/memory_ram) (G)
# ffd_param_clear_n_LENGTH193 (Instance: risc_v_top_i/id_ex_datapath_ffd) (G)
# double_multiplexor_param_LENGTH32_0 (Instance: risc_v_top_i/forwardB_mux) (G)
# uart_IP_DATA_WIDTH32 (Instance: risc_v_top_i/uart_IP_module) (G)
# adder_LENGTH32 (Instance: risc_v_top_i/adder_pc_4) (G)
# FSM_UART_Rx (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/rx_uart/FSM_Rx) (G)
# uart_full_duplex (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex) (G)
# multiplexor_param_LENGTH64 (Instance: risc_v_top_i/mult_if_pipe) (G)
# ffd_param_pc_risk_LENGTH32_RST_VAL32h00400000 (Instance: risc_v_top_i/ff_pc) (G)
# UART_Rx_baud_rate5210 (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/rx_uart) (G)
# branch_prediction_DATA_WIDTH32_BRANCH_NO8 (Instance: risc_v_top_i/branch_predictor) (G)
# master_memory_map_DATA_WIDTH32_ADDR_WIDTH7 (Instance: risc_v_top_i/memory_map) (G)
# ffd_param_clear_n_LENGTH133 (Instance: risc_v_top_i/mem_wb_datapath_ffd) (G)
# risc_v_top (Instance: risc_v_top_i) (G)
# control_unit (Instance: risc_v_top_i/cu) (G)
# forward_unit (Instance: risc_v_top_i/fwd_unit) (G)
# uart_tx_fsm (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/tx_uart/tx_fsm) (G)
# ALU_LENGTH32 (Instance: risc_v_top_i/alu_block) (G)
# double_multiplexor_param_LENGTH32_3 (Instance: risc_v_top_i/mult_alu_param) (G)
# adder_LENGTH32_1 (Instance: risc_v_top_i/adder_pc_prev_4) (G)
# double_multiplexor_param_LENGTH32 (Instance: risc_v_top_i/forwardA_mux) (G)
# register_file (Instance: risc_v_top_i/reg_file) (G)
# adder_LENGTH32_0 (Instance: risc_v_top_i/adder_jump) (G)
# ffd_param_clear_n_LENGTH64 (Instance: risc_v_top_i/if_id_datapath_ffd) (G)
# double_multiplexor_param_LENGTH32_1 (Instance: risc_v_top_i/mult_fwd_SW) (G)
# ALU_control (Instance: risc_v_top_i/alu_ctrl) (G)
# branch_control_unit (Instance: risc_v_top_i/branch_control) (G)
# Delayer_YY250000 (Instance: risc_v_top_i/uart_IP_module/UART_full_duplex/tx_uart/delay_5ms) (G)
# double_multiplexor_param_LENGTH32_2 (Instance: risc_v_top_i/memory_map/memory_map_mult) (G)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
