
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 24 2023 16:36:19 UTC (Oct 24 2023 16:36:19 UTC)

// Verification Directory fv/risc_v_top 

module risc_v_top(clk_50Mhz, rst_n, rx, tx);
  input clk_50Mhz, rst_n, rx;
  output tx;
  wire clk_50Mhz, rst_n, rx;
  wire tx;
  assign tx = 1'b1;
endmodule

